import type { Lab } from "./types"

export function getMockLabData(testName: string, location: string): Lab[] {
  // In a real app, this would be an API call
  // For demo purposes, we'll return mock data

  // Generate random prices based on the test name to make it seem dynamic
  const basePrice = testName.length * 5 + 20

  return [
    {
      id: "lab1",
      name: "HealthFirst Diagnostics",
      address: "123 Medical Blvd, Cityville",
      distance: 2.3,
      rating: 4.8,
      reviewCount: 243,
      testPrice: basePrice - 5,
      openingHours: "Mon-Sat: 7:00 AM - 7:00 PM",
      phone: "(555) 123-4567",
      accreditations: ["NABL", "CAP", "ISO 15189"],
      services: ["Blood Tests", "Imaging", "Pathology"],
    },
    {
      id: "lab2",
      name: "MediLab Plus",
      address: "456 Health Street, Cityville",
      distance: 3.7,
      rating: 4.5,
      reviewCount: 187,
      testPrice: basePrice - 10,
      openingHours: "Mon-Sun: 8:00 AM - 8:00 PM",
      phone: "(555) 234-5678",
      accreditations: ["NABL", "ISO 15189"],
      services: ["Blood Tests", "Urine Analysis", "Microbiology"],
    },
    {
      id: "lab3",
      name: "City Central Diagnostics",
      address: "789 Central Ave, Cityville",
      distance: 5.1,
      rating: 4.7,
      reviewCount: 312,
      testPrice: basePrice,
      openingHours: "Mon-Fri: 7:00 AM - 9:00 PM",
      phone: "(555) 345-6789",
      accreditations: ["NABL", "CAP", "ISO 15189", "CLIA"],
      services: ["Blood Tests", "Imaging", "Cardiology", "Neurology"],
    },
    {
      id: "lab4",
      name: "QuickTest Labs",
      address: "101 Express Lane, Cityville",
      distance: 6.8,
      rating: 4.2,
      reviewCount: 156,
      testPrice: basePrice - 15,
      openingHours: "Mon-Sun: 24 Hours",
      phone: "(555) 456-7890",
      accreditations: ["NABL", "ISO 15189"],
      services: ["Blood Tests", "Rapid Testing", "Home Collection"],
    },
    {
      id: "lab5",
      name: "Premium Diagnostics Center",
      address: "202 Luxury Blvd, Cityville",
      distance: 8.4,
      rating: 4.9,
      reviewCount: 278,
      testPrice: basePrice + 25,
      openingHours: "Mon-Sat: 8:00 AM - 6:00 PM",
      phone: "(555) 567-8901",
      accreditations: ["NABL", "CAP", "ISO 15189", "JCI"],
      services: ["Blood Tests", "Imaging", "Genetic Testing", "Executive Health Checkups"],
    },
    {
      id: "lab6",
      name: "Neighborhood Medical Lab",
      address: "303 Local Street, Cityville",
      distance: 1.5,
      rating: 4.3,
      reviewCount: 124,
      testPrice: basePrice - 8,
      openingHours: "Mon-Fri: 8:00 AM - 5:00 PM",
      phone: "(555) 678-9012",
      accreditations: ["NABL", "ISO 15189"],
      services: ["Blood Tests", "Basic Health Panels"],
    },
    {
      id: "lab7",
      name: "University Research Labs",
      address: "404 Academic Way, Cityville",
      distance: 12.3,
      rating: 4.6,
      reviewCount: 201,
      testPrice: basePrice + 10,
      openingHours: "Mon-Fri: 9:00 AM - 5:00 PM",
      phone: "(555) 789-0123",
      accreditations: ["NABL", "CAP", "ISO 15189", "CLIA"],
      services: ["Blood Tests", "Research Studies", "Specialized Testing"],
    },
    {
      id: "lab8",
      name: "Budget Friendly Diagnostics",
      address: "505 Value Road, Cityville",
      distance: 9.7,
      rating: 4.0,
      reviewCount: 98,
      testPrice: basePrice - 20,
      openingHours: "Mon-Sat: 8:00 AM - 8:00 PM",
      phone: "(555) 890-1234",
      accreditations: ["NABL", "ISO 15189"],
      services: ["Blood Tests", "Basic Panels", "Affordable Screenings"],
    },
  ]
}
